### ISSUE TITLE
sphere loss

### ISSUE THREAD

**Issue by icefish1996** [DLLXW/DIGIX-ImageRetrieval#1]
when using spere loss, meet with the following error
Traceback (most recent call last):
  File "/home/ligh/hby/huawei_DIGIX/DIGIX-ImageRetrieval-master/train_arcLoss.py", line 183, in <module>
    scheduler=scheduler,
  File "/home/ligh/hby/huawei_DIGIX/DIGIX-ImageRetrieval-master/train_arcLoss.py", line 54, in train_model
    out= model(inputs,labels)
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data_2t/home/ligh/hby/huawei_DIGIX/DIGIX-ImageRetrieval-master/modeling/models.py", line 103, in forward
    logits = self.final(feature)
  File "/home/ligh/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'label'

**Comment by DLLXW** [comment]
The number of pictures needs to be divisible by batch size. So you can change the batchsize,
